export const state = {
  mailListEl: null,
  searchMode: false,
  searchQuery: "",
  editorInitialized: false,
  folderMap: new Map(),
  inboxFolderId: null,
  lastEmailPreview: null,
  selectedMails: new Set(),
  activeMailItem: null,
  previewCache: new Map(),
  folderCache: new Map(),
  lastSelectedIndex: null,
  previewRequest: 0,
  currentFolder: "inbox",
  nextPage: window.__MAIL_NEXT_PAGE__ ?? null,
  loadingMore: false,
  scrollTimer: null,
  currentIndex: -1,
  attachments: [],
  attachmentObjectUrls: new Map(),
  recipients: [],
  firstDelta: true,
  processedIds: new Set(),
  deltaTimer: null,
  draggedMails: [],
  oneDriveHistory: [],
  oneDriveCache: new Map(),
  currentFolderMenu: null,
  viewerAttachments: [],
  currentAttachment: 0,
  searchTimer: null,
  mailSearchAbort: null,
  recipientAbort: null,
  previewAbort: null,
  folderAbort: null,
  deltaAbort: null,
};